# Generated by Django 4.2.7 on 2025-12-01 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='资源名称')),
                ('course', models.CharField(max_length=100, verbose_name='所属课程')),
                ('college', models.CharField(max_length=100, verbose_name='所属学院')),
                ('description', models.TextField(blank=True, null=True, verbose_name='资源简介')),
                ('file_url', models.CharField(max_length=255, verbose_name='资源文件路径')),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
                ('uploader_role', models.CharField(choices=[('student', '学生'), ('teacher', '老师')], max_length=10)),
                ('click_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, '审核中'), (1, '已通过'), (2, '已拒绝')], default=0)),
                ('reject_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '学习资源',
                'verbose_name_plural': '学习资源',
                'db_table': 'learning_resource',
            },
        ),
    ]
