# Generated by Django 4.2.7 on 2025-12-02 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceClickRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_records', to='learning_resource.learningresource', verbose_name='资源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '资源点击记录',
                'verbose_name_plural': '资源点击记录',
                'db_table': 'resource_click_record',
            },
        ),
        migrations.CreateModel(
            name='ResourceFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='learning_resource.learningresource', verbose_name='资源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '资源收藏',
                'verbose_name_plural': '资源收藏',
                'db_table': 'resource_favorite',
                'unique_together': {('user', 'resource')},
            },
        ),
        migrations.AddConstraint(
            model_name='resourceclickrecord',
            constraint=models.UniqueConstraint(fields=('user', 'resource'), name='unique_user_resource_click'),
        ),
    ]
