# Generated by Django 4.2.7 on 2025-12-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resource', '0002_resourceclickrecord_resourcefavorite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresource',
            name='file_url',
        ),
        migrations.AddField(
            model_name='learningresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='learning_resources/', verbose_name='资源文件'),
        ),
    ]
