# Generated by Django 4.2.7 on 2025-12-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resource', '0003_remove_learningresource_file_url_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resourceclickrecord',
            name='unique_user_resource_click',
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='learning_resource/', verbose_name='资源文件'),
        ),
        migrations.AddIndex(
            model_name='resourceclickrecord',
            index=models.Index(fields=['user', 'resource'], name='resource_cl_user_id_2f5b02_idx'),
        ),
    ]
