from django.urls import path

from .views import (
    ExamAssignmentAvailableView,
    ExamAssignmentListCreateView,
    ExamAssignmentStartView,
    ExamAssignmentSubmissionsView,
    PracticeAttemptDetailView,
    PracticeAttemptHistoryView,
    PracticeAttemptOngoingView,
    PracticeAttemptPendingReviewView,
    PracticeAttemptReviewView,
    PracticeAttemptSaveAnswersView,
    PracticeAttemptStartView,
    PracticeAttemptSubmitView,
    PracticeAttemptTeacherDetailView,
    PracticeAttemptTeacherPendingReviewView,
    PracticeAttemptTeacherStudentPendingView,
    QuestionPracticeView,
    TeacherQuestionSubjectSummaryView,
    TeacherQuestionCreateView,
    QuestionImageUploadView,
    TeacherQuestionDraftDetailView,
    TeacherQuestionDraftListView,
    TeacherQuestionDraftPublishView,
    TeacherQuestionListView,
    TeacherDashboardOverviewView,
    StudentDashboardOverviewView,
    TeacherQuestionDetailView,
    SubjectListView,
    WrongBookEntryDetailView,
    WrongBookEntryListView,
)

urlpatterns = [
    path('subjects/', SubjectListView.as_view()),
    path('practice/', QuestionPracticeView.as_view()),
    path('practice/attempts/start/', PracticeAttemptStartView.as_view()),
    path('practice/attempts/ongoing/', PracticeAttemptOngoingView.as_view()),
    path('practice/attempts/pending-review/', PracticeAttemptPendingReviewView.as_view()),
    path('practice/attempts/pending-review/teacher/', PracticeAttemptTeacherPendingReviewView.as_view()),
    path('practice/attempts/pending-review/teacher/students/', PracticeAttemptTeacherStudentPendingView.as_view()),
    path('practice/attempts/history/', PracticeAttemptHistoryView.as_view()),
    path('practice/attempts/<int:attempt_id>/', PracticeAttemptDetailView.as_view()),
    path('practice/attempts/<int:attempt_id>/save/', PracticeAttemptSaveAnswersView.as_view()),
    path('practice/attempts/<int:attempt_id>/submit/', PracticeAttemptSubmitView.as_view()),
    path('practice/attempts/<int:attempt_id>/teacher/', PracticeAttemptTeacherDetailView.as_view()),
    path('practice/attempts/<int:attempt_id>/review/', PracticeAttemptReviewView.as_view()),
    path('wrong-book/items/', WrongBookEntryListView.as_view()),
    path('wrong-book/items/<int:entry_id>/', WrongBookEntryDetailView.as_view()),
    path('teacher/questions/', TeacherQuestionListView.as_view()),
    path('teacher/questions/<int:question_id>/', TeacherQuestionDetailView.as_view()),
    path('teacher/questions/subjects/', TeacherQuestionSubjectSummaryView.as_view()),
    path('teacher/questions/create/', TeacherQuestionCreateView.as_view()),
    path('teacher/questions/image-upload/', QuestionImageUploadView.as_view()),
    path('teacher/questions/drafts/', TeacherQuestionDraftListView.as_view()),
    path('teacher/questions/drafts/<int:draft_id>/', TeacherQuestionDraftDetailView.as_view()),
    path('teacher/questions/drafts/<int:draft_id>/publish/', TeacherQuestionDraftPublishView.as_view()),
        path('dashboard/teacher/overview/', TeacherDashboardOverviewView.as_view()),
        path('dashboard/student/overview/', StudentDashboardOverviewView.as_view()),
    path('assignments/', ExamAssignmentListCreateView.as_view()),
    path('assignments/available/', ExamAssignmentAvailableView.as_view()),
    path('assignments/<int:assignment_id>/start/', ExamAssignmentStartView.as_view()),
    path('assignments/<int:assignment_id>/submissions/', ExamAssignmentSubmissionsView.as_view()),
]
