# Generated by Django 4.2.7 on 2025-12-01 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysuser',
            options={'verbose_name': '系统用户', 'verbose_name_plural': '系统用户'},
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '禁用')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='用户名'),
        ),
    ]
