# Generated by Django 4.2.7 on 2025-12-01 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_sysuser_options_remove_sysuser_login_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='工号')),
                ('college', models.CharField(blank=True, max_length=100, null=True, verbose_name='学院')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='职称')),
                ('research_area', models.CharField(blank=True, max_length=200, null=True, verbose_name='研究方向')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '教师信息',
                'db_table': 'teacher_profile',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='学号')),
                ('college', models.CharField(blank=True, max_length=100, null=True, verbose_name='学院')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('grade', models.CharField(blank=True, max_length=20, null=True, verbose_name='年级')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学生信息',
                'db_table': 'student_profile',
            },
        ),
    ]
