# Generated by Django 4.2.7 on 2025-12-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_sysuser_login_date_remove_sysuser_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysuser',
            name='Login_date',
        ),
        migrations.RemoveField(
            model_name='sysuser',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='sysuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('admin', '管理员')], default='student', max_length=20, verbose_name='用户角色'),
        ),
    ]
