# Generated by Django 3.0.3 on 2025-12-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_practiceattempt_practiceattemptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceattempt',
            name='is_review_required',
            field=models.BooleanField(default=False, verbose_name='待教师批阅'),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='obtained_score',
            field=models.PositiveIntegerField(default=0, verbose_name='得分'),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='total_score',
            field=models.PositiveIntegerField(default=0, verbose_name='总分'),
        ),
        migrations.AlterField(
            model_name='practiceattempt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='practiceattemptitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
