# Generated by Django 4.2.7 on 2025-12-02 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20251202_2051'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='考试标题')),
                ('question_type', models.CharField(choices=[('objective', '客观题'), ('subjective', '主观题')], max_length=16, verbose_name='题型')),
                ('question_count', models.PositiveIntegerField(default=10, verbose_name='题目数量')),
                ('duration_seconds', models.PositiveIntegerField(default=1800, verbose_name='考试时长(秒)')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('closed', '已结束')], default='published', max_length=16, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='发布教师')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exam.subject', verbose_name='科目')),
            ],
            options={
                'verbose_name': '考试任务',
                'verbose_name_plural': '考试任务',
                'db_table': 'exam_assignment',
                'ordering': ('-start_time', '-id'),
            },
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='mode',
            field=models.CharField(choices=[('practice', '练习'), ('exam', '考试')], default='practice', max_length=16, verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.examassignment', verbose_name='关联考试'),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='review_comment',
            field=models.TextField(blank=True, null=True, verbose_name='教师评语'),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='批阅时间'),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attempts', to=settings.AUTH_USER_MODEL, verbose_name='批阅教师'),
        ),
    ]
