# Generated by Django 3.0.3 on 2025-12-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_examassignment_practiceattempt_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceattemptitem',
            name='awarded_score',
            field=models.PositiveIntegerField(default=0, verbose_name='得分'),
        ),
    ]
