# Generated by Django 4.2.7 on 2025-12-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0011_alter_examassignment_id_alter_practiceattempt_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examassignment",
            name="per_question_score",
            field=models.PositiveIntegerField(default=10, verbose_name="单题分值"),
        ),
        migrations.AddField(
            model_name="examassignment",
            name="question_ids",
            field=models.JSONField(blank=True, default=list, verbose_name="固定题目列表"),
        ),
        migrations.AddField(
            model_name="practiceattemptitem",
            name="expected_score",
            field=models.PositiveIntegerField(default=0, verbose_name="题目分值"),
        ),
    ]
