# Generated by Django 4.2.7 on 2025-12-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_examassignment_question_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examassignment',
            name='question_type',
            field=models.CharField(choices=[('objective', '客观题'), ('subjective', '主观题'), ('mixed', '综合试卷')], max_length=16, verbose_name='题型'),
        ),
        migrations.AlterField(
            model_name='practiceattempt',
            name='question_type',
            field=models.CharField(choices=[('objective', '客观题'), ('subjective', '主观题'), ('mixed', '综合试卷')], max_length=16, verbose_name='题型'),
        ),
    ]
